### ISSUE TITLE
java.lang.RuntimeException: Parcel android.os.Parcel: Unmarshalling unknown type code

### ISSUE THREAD

**Issue by djstrong** [Cielsk/clearable-edittext#1]
This widget causes exception:
```
java.lang.RuntimeException: Parcel android.os.Parcel@d2aa90f: Unmarshalling unknown type code 37 at offset 844
    at android.os.Parcel.readValue(Parcel.java:2222)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
    at android.os.Parcel.readSparseArray(Parcel.java:1868)
    at android.os.Parcel.readValue(Parcel.java:2203)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
    at android.os.BaseBundle.unparcel(BaseBundle.java:221)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
    at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1979)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1022)
    at android.app.Activity.performRestoreInstanceState(Activity.java:977)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1161)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5221) 
    at java.lang.reflect.Method.invoke(Native Method)
```

Steps to reproduce:
1. In Dev tools/setting choose "Don't keep activities".
2. Run app with ClearableEditText and write something into the widget, so the clear button appears.
3. Click Home button.
4. Restore the app from running apps screen.

It is related to Parcelable. I have seen in the code `readByte()`, but nowhere writing.

**Comment by Cielsk** [comment]
Fixed in #2
