### ISSUE TITLE
Crash when applying theme to parent TextInputLayout

### ISSUE THREAD

**Issue by DFreds** [Cielsk/clearable-edittext#12]
I'm trying to customize the color of the EditText to not use the default accent color for the underline and floating label. I am able to achieve this with regular edit text views utilizing the `android:theme` property. However, this library causes a crash when attempting to do the same thing. When I remove the `android:theme` property, it does not crash anymore (but the color is wrong).

Layout:
```xml
        <android.support.design.widget.TextInputLayout
            android:id="@+id/input"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginTop="24dp"
            android:layout_marginEnd="16dp"
            android:theme="@style/Login.Form"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/input_header">

            <com.cielyang.android.clearableedittext.ClearableTextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/input_hint"
                android:inputType="textCapWords|textAutoComplete"
                android:maxLines="1"/>
        </android.support.design.widget.TextInputLayout>
```

Style:

```xml
    <style name="Login.Form" parent="TextAppearance.AppCompat">
        <!-- State: Inactive -->
        <!-- Affects: Label -->
        <item name="android:textColorHint">@color/grey4</item>
        <item name="android:textSize">16sp</item>

        <!-- State: Activated -->
        <!-- Affects: Label, Underline -->
        <item name="colorAccent">@color/plum</item>
        <item name="colorControlActivated">@color/plum</item>

        <!-- State: Normal -->
        <!-- Affects: Label, Underline -->
        <item name="colorControlNormal">@android:color/black</item>
    </style>
```

Stack trace:

```
2019-01-16 12:13:22.873 24550-24550/com.place E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.place, PID: 24550
    android.view.InflateException: Binary XML file line #89: Binary XML file line #89: Error inflating class com.cielyang.android.clearableedittext.ClearableTextInputEditText
    Caused by: android.view.InflateException: Binary XML file line #89: Error inflating class com.cielyang.android.clearableedittext.ClearableTextInputEditText
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.place.MyFragment.onCreateView(MyFragment.kt:27)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}
        at android.content.res.TypedArray.getColor(TypedArray.java:469)
        at android.widget.TextView.<init>(TextView.java:892)
        at android.widget.EditText.<init>(EditText.java:88)
        at android.widget.EditText.<init>(EditText.java:84)
        at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:64)
        at android.support.design.widget.TextInputEditText.<init>(TextInputEditText.java:45)
        at com.cielyang.android.clearableedittext.ClearableTextInputEditText.<init>(ClearableTextInputEditText.java:38)
        at com.cielyang.android.clearableedittext.ClearableTextInputEditText.<init>(ClearableTextInputEditText.java:34)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.place.MyFragment.onCreateView(MyFragment.kt:27) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by DFreds** [comment]
I figured this out. It was because my style was extending the TextAppearance.AppCompat. I don't know why it isn't crashing when I use a normal TextInputEditText, but this is good enough for me. I'll close it
